DEBUG = True
TEMPLATE_DEBUG = DEBUG
EMAIL_HOST = "localhost"
DEFAULT_FROM_EMAIL = "seb.bacon@gmail.com"
OFFLINE = False

DATABASE_NAME = 'worderator'
DATABASE_USER = 'seb'
DATABASE_PASSWORD = 'f0aoosd'
DATABASE_HOST = 'localhost'
GOOGLE_ANALYTICS_ID = ""

SPLITSIZE = 3
PREFER_MAXSIZE = 7
HARD_MAXSIZE = 14
FALLBACK_DB="src/british"
